# Analysis of the NYC 311 Dataset

The NYC 311 dataset contains records of non-emergency service requests made by residents of New York City. These complaints are submitted via phone, web, or mobile app and include issues like noise complaints, illegal parking, blocked driveways, and more.

Each record typically includes:
- The type of complaint
- Date and time the complaint was created and closed
- The location of the incident (ZIP code, street address)
- The agency responsible
- Status and resolution details

You will use your knowledge of Pandas to do the following activity.

### Step 1: Load and Inspect the NYC 311 Dataset

In this step, we'll load the NYC 311 complaint dataset from CSV and explore its structure.

- Call the DataFrame `df_311`
- Check how many rows and columns it contains.
- View the first 5 rows to understand the kind of data we're working with.

In [29]:
# Your code here
import pandas as pd

df_311=pd.read_csv('NYC311data_cleaned.csv')
print('First 100 rows:\n')
df_311.head(100)

First 100 rows:

,Unique Key,Created Date,Closed Date,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,Street Name,Cross Street 1,Cross Street 2,Address Type,Status,Due Date,Resolution Description,Resolution Action Updated Date,Community Board
0,31685705,10-05-15 22:45,10-06-15 2:09,Blocked Driveway,No Access,Street/Sidewalk,11373,43-31 ELBERTSON STREET,ELBERTSON STREET,LAMONT AVENUE,43 AVENUE,ADDRESS,Closed,10-06-15 6:45,The Police Department responded to the complai...,10-06-15 2:09,04 QUEENS
1,31426484,08/30/2015 09:04:52 PM,08/30/2015 11:53:46 PM,Noise - Street/Sidewalk,Loud Talking,Street/Sidewalk,10030,100 WEST 141 STREET,WEST 141 STREET,LENOX AVENUE,7 AVENUE,ADDRESS,Closed,08/31/2015 05:04:52 AM,The Police Department responded to the complai...,08/30/2015 11:53:46 PM,10 MANHATTAN
2,31473909,09-06-15 23:56,09-07-15 7:30,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10034,73 VERMILYEA AVENUE,VERMILYEA AVENUE,ACADEMY STREET,WEST 204 STREET,ADDRESS,Closed,09-07-15 7:56,The Police Department responded to the complai...,09-07-15 7:30,12 MANHATTAN
3,31530153,09/14/2015 11:05:21 AM,09/14/2015 12:52:54 PM,Illegal Parking,Posted Parking Sign Violation,Street/Sidewalk,11385,NaN,NaN,NaN,NaN,INTERSECTION,Closed,09/14/2015 07:05:21 PM,The Police Department responded and upon arriv...,09/14/2015 12:52:54 PM,05 QUEENS
4,31562497,09/18/2015 09:53:11 PM,09/19/2015 04:34:07 AM,Derelict Vehicle,With License Plate,Street/Sidewalk,11235,611 BANNER AVENUE,BANNER AVENUE,BRIGHTON 6 STREET,BRIGHTON 7 STREET,ADDRESS,Closed,09/19/2015 05:53:11 AM,The Police Department responded to the complai...,09/19/2015 04:34:07 AM,13 BROOKLYN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,32309640,12/31/2015 10:03:00 PM,12/31/2015 10:26:42 PM,Noise - Street/Sidewalk,Loud Talking,Street/Sidewalk,11208,165 HIGHLAND PLACE,HIGHLAND PLACE,ARLINGTON AVENUE,FULTON STREET,ADDRESS,Closed,01-01-16 6:03,The Police Department responded to the complai...,12/31/2015 10:26:42 PM,05 BROOKLYN
96,30998247,07-03-15 21:39,07-03-15 23:06,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10031,NaN,NaN,NaN,NaN,INTERSECTION,Closed,07-04-15 5:39,The Police Department responded to the complai...,07-03-15 23:06,09 MANHATTAN
97,30642574,05/17/2015 11:26:18 AM,05/17/2015 01:08:05 PM,Blocked Driveway,No Access,Street/Sidewalk,10473,329 UNDERHILL AVENUE,UNDERHILL AVENUE,O'BRIEN AVENUE,PATTERSON AVENUE,ADDRESS,Closed,05/17/2015 07:26:18 PM,The Police Department issued a summons in resp...,05/17/2015 01:08:05 PM,09 BRONX
98,31937554,11-08-15 16:03,11-08-15 16:10,Illegal Parking,Posted Parking Sign Violation,Street/Sidewalk,10002,303 BROOME STREET,BROOME STREET,ELDRIDGE STREET,FORSYTH STREET,ADDRESS,Closed,11-09-15 0:03,Your request can not be processed at this time...,11-08-15 16:10,03 MANHATTAN
99,30672371,05/21/2015 11:50:19 PM,05/22/2015 01:28:31 AM,Illegal Parking,Blocked Sidewalk,Street/Sidewalk,11373,NaN,NaN,NaN,NaN,INTERSECTION,Closed,05/22/2015 07:50:19 AM,The Police Department responded to the complai...,05/22/2015 01:28:31 AM,04 QUEENS

In [30]:
print('Shape of DataFrame:\n', df_311.shape)
print('\n')
print('Column names:\n  ',df_311.columns.tolist())

Shape of DataFrame:
 (89396, 17)


Column names:
   ['Unique Key', 'Created Date', 'Closed Date', 'Complaint Type', 'Descriptor', 'Location Type', 'Incident Zip', 'Incident Address', 'Street Name', 'Cross Street 1', 'Cross Street 2', 'Address Type', 'Status', 'Due Date', 'Resolution Description', 'Resolution Action Updated Date', 'Community Board']

### Step 2: Convert Date Columns to Datetime

In this step, we'll convert the following columns to proper datetime format:

- `Created Date`
- `Closed Date`
- `Due Date`
- `Resolution Action Updated Date`

Since the dataset contains **mixed date formats**, we should **not specify a date format**. Instead, use `errors='coerce'` to safely handle problematic rows (they will become `NaT`).

We may get warnings during this step — **we may ignore them**. The warning may ask we to specify a format, but since there are different kinds of date/time formats in those columns, letting Pandas to fix them is the most robust method.

In [31]:
# Convert all relevant date columns
df_311['Created Date'] = pd.to_datetime(df_311['Created Date'], errors='coerce')
df_311['Closed Date'] = pd.to_datetime(df_311['Closed Date'], errors='coerce')
df_311['Due Date'] = pd.to_datetime(df_311['Due Date'], errors='coerce')
df_311['Resolution Action Updated Date'] = pd.to_datetime(df_311['Resolution Action Updated Date'], errors='coerce')

# Check a few of the columns after conversion
df_311[['Created Date', 'Closed Date']].head()

/var/folders/sk/b5gcsk2d1yqbpg1wc19zbq480000gp/T/ipykernel_34710/3897271777.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_311['Created Date'] = pd.to_datetime(df_311['Created Date'], errors='coerce')
/var/folders/sk/b5gcsk2d1yqbpg1wc19zbq480000gp/T/ipykernel_34710/3897271777.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_311['Closed Date'] = pd.to_datetime(df_311['Closed Date'], errors='coerce')
/var/folders/sk/b5gcsk2d1yqbpg1wc19zbq480000gp/T/ipykernel_34710/3897271777.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_311['Due Date'] = pd.to_datetime(df_311['Due Date'], errors='coerce')
/var/folders/sk/b5gcsk2d1yqbpg1wc19zbq480000gp/T/ipykernel_34710/3897271777.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_311['Resolution Action Updated Date'] = pd.to_datetime(df_311['Resolution Action Updated Date'], errors='coerce')

         Created Date         Closed Date
0 2015-10-05 22:45:00 2015-10-06 02:09:00
1 2015-08-30 21:04:52 2015-08-30 23:53:46
2 2015-09-06 23:56:00 2015-09-07 07:30:00
3 2015-09-14 11:05:21 2015-09-14 12:52:54
4 2015-09-18 21:53:11 2015-09-19 04:34:07

### Step 3: Sorting Practice Questions to Explore `df_311`

Use the dataset `df_311` to practice various **sorting techniques**.

1. **Basic sorting (ascending)**:  
   - Sort the DataFrame by `Created Date` in ascending order and show the first 5 rows.

2. **Descending sort**:  
   - Sort by `Closed Date` in descending order and display the top 5 complaints with the latest closing times.

3. **Sorting by multiple columns**:  
   - Sort first by `Complaint Type` (A–Z), then by `Created Date` (newest first).

4. **Sorting with a custom function**:  
   - Sort complaints by the **length** of the `Descriptor` column, longest first.

5. **In-place sorting**:  
   - Sort the DataFrame by `Due Date` in-place, then show the last 5 rows.

In [32]:
# 1. Sort the DataFrame by Created Date in ascending order and show the first 5 rows.

df_311_sorted = df_311.sort_values(by='Created Date')
df_311_sorted.head(5)

,Unique Key,Created Date,Closed Date,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,Street Name,Cross Street 1,Cross Street 2,Address Type,Status,Due Date,Resolution Description,Resolution Action Updated Date,Community Board
87211,30283424,2015-03-29 00:33:03,2015-03-29 03:40:20,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,11206,162 THROOP AVENUE,THROOP AVENUE,HOPKINS STREET,ELLERY STREET,ADDRESS,Closed,2015-03-29 08:33:03,The Police Department responded to the complai...,2015-03-29 03:40:20,03 BROOKLYN
34299,30283432,2015-03-29 00:35:28,2015-03-29 04:14:27,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,11233,120 CHAUNCEY STREET,CHAUNCEY STREET,STUYVESANT AVENUE,MALCOLM X BOULEVARD,ADDRESS,Closed,2015-03-29 08:35:28,The Police Department responded to the complai...,2015-03-29 04:14:27,03 BROOKLYN
50645,30280732,2015-03-29 00:37:15,2015-03-29 01:02:39,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,10014,22 9 AVENUE,9 AVENUE,WEST 13 STREET,WEST 14 STREET,ADDRESS,Closed,2015-03-29 08:37:15,The Police Department reviewed your complaint ...,2015-03-29 01:02:39,02 MANHATTAN
19065,30280506,2015-03-29 00:43:16,2015-03-29 04:25:50,Noise - Vehicle,Car/Truck Music,Street/Sidewalk,10028,415 EAST 86 STREET,EAST 86 STREET,1 AVENUE,YORK AVENUE,ADDRESS,Closed,2015-03-29 08:43:16,The Police Department responded and upon arriv...,2015-03-29 04:25:50,08 MANHATTAN
116,30281090,2015-03-29 00:49:27,2015-03-29 04:25:53,Noise - Vehicle,Car/Truck Music,Street/Sidewalk,10028,420 EAST 86 STREET,EAST 86 STREET,1 AVENUE,YORK AVENUE,ADDRESS,Closed,2015-03-29 08:49:27,The Police Department responded and upon arriv...,2015-03-29 04:25:53,08 MANHATTAN

In [33]:
# 2. Sort by Closed Date in descending order and display the top 5 complaints with the latest closing times.
df_311_sorted_closed = df_311.sort_values(by='Closed Date', ascending=False)
print(df_311_sorted_closed.head(5))

       Unique Key        Created Date         Closed Date    Complaint Type  \
6831     32308423 2015-12-31 23:31:40 2016-01-03 16:22:00  Blocked Driveway
47242    32306260 2015-12-31 23:50:57 2016-01-01 10:58:00  Blocked Driveway
59869    32310624 2015-12-31 18:22:08 2016-01-01 08:27:00  Blocked Driveway
17264    32306268 2015-12-31 20:02:03 2016-01-01 07:47:00  Blocked Driveway
2304     32308708 2015-12-31 21:43:01 2016-01-01 07:44:00   Illegal Parking

            Descriptor    Location Type  Incident Zip  \
6831         No Access  Street/Sidewalk         10467
47242        No Access  Street/Sidewalk         10453
59869   Partial Access  Street/Sidewalk         11416
17264        No Access  Street/Sidewalk         10461
2304   Blocked Hydrant  Street/Sidewalk         11220

               Incident Address          Street Name   Cross Street 1  \
6831        3025 WALLACE AVENUE       WALLACE AVENUE      ADEE AVENUE
47242    1770 UNDERCLIFF AVENUE    UNDERCLIFF AVENUE  WEST 176 STREET
59869           97-46 77 STREET            77 STREET        97 AVENUE
17264  1659 WILLIAMSBRIDGE ROAD  WILLIAMSBRIDGE ROAD    PIERCE AVENUE
2304         167 SENATOR STREET       SENATOR STREET    COLONIAL ROAD

        Cross Street 2 Address Type  Status            Due Date  \
6831      BURKE AVENUE      ADDRESS  Closed 2016-01-01 07:31:00
47242  SEDGWICK AVENUE      ADDRESS  Closed 2016-01-01 07:50:00
59869       101 AVENUE      ADDRESS  Closed 2016-01-01 02:22:00
17264  VAN NEST AVENUE      ADDRESS  Closed 2016-01-01 04:02:00
2304   RIDGE BOULEVARD      ADDRESS  Closed 2016-01-01 05:43:00

                                  Resolution Description  \
6831   The Police Department responded to the complai...
47242  The Police Department responded to the complai...
59869  The Police Department responded and upon arriv...
17264  The Police Department responded to the complai...
2304   The Police Department responded and upon arriv...

      Resolution Action Updated Date Community Board
6831             2016-01-03 16:22:00        12 BRONX
47242            2016-01-01 10:58:00        05 BRONX
59869            2016-01-01 08:27:00       09 QUEENS
17264            2016-01-01 07:47:00        11 BRONX
2304             2016-01-01 07:44:00     10 BROOKLYN

In [34]:
# 3. Sort first by Complaint Type (A–Z), then by Created Date (newest first).
df_311_sorted_complaint = df_311.sort_values(by=['Complaint Type', 'Created Date'],ascending=[True,False])
print(df_311_sorted_complaint.head(10))

       Unique Key        Created Date         Closed Date Complaint Type  \
6937     32306470 2015-12-31 22:38:04 2015-12-31 23:04:14   Animal Abuse
4650     32309522 2015-12-31 21:22:54 2015-12-31 22:33:00   Animal Abuse
66899    32310128 2015-12-31 16:59:34 2015-12-31 21:14:28   Animal Abuse
36331    32305067 2015-12-31 14:08:45 2015-12-31 15:02:57   Animal Abuse
82916    32310105 2015-12-31 13:54:38 2015-12-31 14:38:22   Animal Abuse
7477     32300487 2015-12-30 19:02:14 2015-12-31 05:17:50   Animal Abuse
58631    32304177 2015-12-30 15:10:40 2015-12-30 18:47:03   Animal Abuse
50605    32303263 2015-12-30 11:59:33 2015-12-30 16:48:03   Animal Abuse
49402    32300439 2015-12-30 10:59:04 2015-12-30 13:51:11   Animal Abuse
83094    32300440 2015-12-30 09:38:09 2015-12-30 16:34:56   Animal Abuse

                      Descriptor               Location Type  Incident Zip  \
6937                    Tortured  Residential Building/House         11427
4650                   Neglected  Residential Building/House         11415
66899                  Neglected  Residential Building/House         11416
36331                  Neglected  Residential Building/House         10472
82916  Other (complaint details)             Street/Sidewalk         10023
7477                  No Shelter        Residential Building         11422
58631  Other (complaint details)  Residential Building/House         11219
50605                  Neglected  Residential Building/House         11414
49402  Other (complaint details)  Residential Building/House         11211
83094  Other (complaint details)  Residential Building/House         10019

            Incident Address       Street Name      Cross Street 1  \
6937        89-27 218 STREET        218 STREET           89 AVENUE
4650        84-87 129 STREET        129 STREET    KEW GARDENS ROAD
66899       102-04 89 STREET         89 STREET          102 AVENUE
36331  1327 STRATFORD AVENUE  STRATFORD AVENUE     EAST 172 STREET
82916               BROADWAY          BROADWAY      WEST 73 STREET
7477         253-07 147 ROAD          147 ROAD          253 STREET
58631   1572 BAYRIDGE AVENUE   BAYRIDGE AVENUE  NEW UTRECHT AVENUE
50605       149-25 84 STREET         84 STREET          149 AVENUE
49402     214 NORTH 4 STREET    NORTH 4 STREET       DRIGGS AVENUE
83094     145 WEST 55 STREET    WEST 55 STREET        6 1/2 AVENUE

            Cross Street 2 Address Type  Status            Due Date  \
6937             90 AVENUE      ADDRESS  Closed 2016-01-01 06:38:00
4650   METROPOLITAN AVENUE      ADDRESS  Closed 2016-01-01 05:22:00
66899             102 ROAD      ADDRESS  Closed 2016-01-01 00:59:00
36331      EAST 174 STREET      ADDRESS  Closed 2015-12-31 22:08:45
82916       WEST 74 STREET    BLOCKFACE  Closed 2015-12-31 21:54:38
7477           WELLER LANE      ADDRESS  Closed 2015-12-31 03:02:14
58631            16 AVENUE      ADDRESS  Closed 2015-12-30 23:10:40
50605           151 AVENUE      ADDRESS  Closed 2015-12-30 19:59:33
49402      ROEBLING STREET      ADDRESS  Closed 2015-12-30 18:59:04
83094             7 AVENUE      ADDRESS  Closed 2015-12-30 17:38:09

                                  Resolution Description  \
6937   The Police Department responded to the complai...
4650   The Police Department responded to the complai...
66899  The Police Department responded to the complai...
36331  The Police Department responded to the complai...
82916  The Police Department responded to the complai...
7477   The Police Department responded to the complai...
58631  The Police Department responded to the complai...
50605  The Police Department responded to the complai...
49402  The Police Department responded to the complai...
83094  The Police Department responded to the complai...

      Resolution Action Updated Date Community Board
6937             2015-12-31 23:04:14       13 QUEENS
4650             2015-12-31 22:33:00       09 QUEENS
66899            2015-12-31 21:14:28       09 QUEENS
36331            2015-12-31 15:02:57        09 BRONX
82916            2015-12-31 14:38:22    07 MANHATTAN
7477             2015-12-31 05:17:50       13 QUEENS
58631            2015-12-30 18:47:03     11 BROOKLYN
50605            2015-12-30 16:48:03       10 QUEENS
49402            2015-12-30 13:51:11     01 BROOKLYN
83094            2015-12-30 16:34:56    05 MANHATTAN

In [35]:
# 4. Sort complaints by the length of the Descriptor column, longest first.

df_311.sort_values(by='Descriptor', key=lambda x:x.str.len(),ascending=False).head()

,Unique Key,Created Date,Closed Date,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,Street Name,Cross Street 1,Cross Street 2,Address Type,Status,Due Date,Resolution Description,Resolution Action Updated Date,Community Board
12336,31851995,2015-10-23 02:07:16,2015-10-23 03:54:31,Illegal Parking,Double Parked Blocking Traffic,Street/Sidewalk,11374,67-63 WOODHAVEN BOULEVARD,WOODHAVEN BOULEVARD,67 DRIVE,68 AVENUE,ADDRESS,Closed,2015-10-23 10:07:16,The Police Department responded to the complai...,2015-10-23 03:54:23,06 QUEENS
86521,30304791,2015-03-31 12:06:32,2015-03-31 13:02:05,Illegal Parking,Double Parked Blocking Traffic,Street/Sidewalk,11209,86 STREET,86 STREET,3 AVENUE,4 AVENUE,BLOCKFACE,Closed,2015-03-31 20:06:32,The Police Department responded to the complai...,2015-03-31 13:02:05,10 BROOKLYN
9055,31502050,2015-09-10 14:20:00,2015-09-10 18:50:00,Illegal Parking,Double Parked Blocking Traffic,Street/Sidewalk,11693,NaN,NaN,NaN,NaN,INTERSECTION,Closed,2015-09-10 22:20:00,The Police Department issued a summons in resp...,2015-09-10 18:50:00,14 QUEENS
61810,31323271,2015-08-16 10:18:43,2015-08-16 12:34:32,Illegal Parking,Double Parked Blocking Vehicle,Street/Sidewalk,10026,218 WEST 116 STREET,WEST 116 STREET,7 AVENUE,8 AVENUE,ADDRESS,Closed,2015-08-16 18:18:43,The Police Department responded to the complai...,2015-08-16 12:34:32,10 MANHATTAN
3461,30444489,2015-04-20 18:54:31,2015-04-20 20:59:30,Illegal Parking,Double Parked Blocking Traffic,Street/Sidewalk,10034,101 POST AVENUE,POST AVENUE,WEST 204 STREET,WEST 207 STREET,ADDRESS,Closed,2015-04-21 02:54:31,The Police Department responded to the complai...,2015-04-20 20:59:30,12 MANHATTAN

In [36]:
# 5. Sort the DataFrame by Due Date in-place, then show the last 5 rows.
df_311.sort_values(by=['Due Date'],inplace=True)
df_311.tail()

,Unique Key,Created Date,Closed Date,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,Street Name,Cross Street 1,Cross Street 2,Address Type,Status,Due Date,Resolution Description,Resolution Action Updated Date,Community Board
47242,32306260,2015-12-31 23:50:57,2016-01-01 10:58:00,Blocked Driveway,No Access,Street/Sidewalk,10453,1770 UNDERCLIFF AVENUE,UNDERCLIFF AVENUE,WEST 176 STREET,SEDGWICK AVENUE,ADDRESS,Closed,2016-01-01 07:50:00,The Police Department responded to the complai...,2016-01-01 10:58:00,05 BRONX
77179,32305071,2015-12-31 23:52:58,2016-01-01 07:41:00,Blocked Driveway,No Access,Street/Sidewalk,11372,34-06 73 STREET,73 STREET,34 AVENUE,35 AVENUE,ADDRESS,Closed,2016-01-01 07:52:00,The Police Department responded and upon arriv...,2016-01-01 07:41:00,03 QUEENS
41975,32306559,2015-12-31 23:55:32,2016-01-01 01:53:00,Illegal Parking,Blocked Hydrant,Street/Sidewalk,10032,524 WEST 169 STREET,WEST 169 STREET,AMSTERDAM AVENUE,AUDUBON AVENUE,ADDRESS,Closed,2016-01-01 07:55:00,The Police Department issued a summons in resp...,2016-01-01 01:53:00,12 MANHATTAN
80818,32306529,2015-12-31 23:56:58,2016-01-01 03:24:00,Illegal Parking,Blocked Sidewalk,Street/Sidewalk,11373,87-14 57 ROAD,57 ROAD,SEABURY STREET,HOFFMAN DRIVE,ADDRESS,Closed,2016-01-01 07:56:00,The Police Department responded and upon arriv...,2016-01-01 03:24:00,04 QUEENS
15623,32310363,2015-12-31 23:59:45,2016-01-01 00:55:00,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10034,71 VERMILYEA AVENUE,VERMILYEA AVENUE,ACADEMY STREET,WEST 204 STREET,ADDRESS,Closed,2016-01-01 07:59:00,The Police Department responded and upon arriv...,2016-01-01 00:55:00,12 MANHATTAN

### Step 4: Filtering Practice Questions to Explore `df_311`

Use the dataset `df_311` to answer the following questions by applying **filtering techniques** covered in this module.

1. **Boolean indexing**:  
   - Show all rows where the status is `"Closed"`.

2. **isin() for multiple values**:  
   - Show complaints where the complaint type is either `"Illegal Parking"`, `"Noise - Street/Sidewalk"`, or `"Blocked Driveway"`.

3. **Multiple conditions**:  
   - Show `"Blocked Driveway"` complaints where the incident ZIP is either `10007` or `10307`.

4. **String method – startswith()**:  
   - Find all complaints where the street name starts with the letter `'E'`.

5. **iloc[]**:  
   - Display the first 3 rows and the 2nd to 5th columns using integer-based indexing.

6. **loc[]**:  
   - Use label-based selection to show `Complaint Type`, `Created Date`, and `Status` for ZIP code `11373`.

7. **between()**:  
   - Filter complaints where the `Created Date` falls between **October 1, 2015** and **October 2, 2015**.

In [37]:
# 1. Show all rows where the status is "Closed".
df_311[df_311['Status']=='Closed']

,Unique Key,Created Date,Closed Date,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,Street Name,Cross Street 1,Cross Street 2,Address Type,Status,Due Date,Resolution Description,Resolution Action Updated Date,Community Board
87211,30283424,2015-03-29 00:33:03,2015-03-29 03:40:20,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,11206,162 THROOP AVENUE,THROOP AVENUE,HOPKINS STREET,ELLERY STREET,ADDRESS,Closed,2015-03-29 08:33:03,The Police Department responded to the complai...,2015-03-29 03:40:20,03 BROOKLYN
34299,30283432,2015-03-29 00:35:28,2015-03-29 04:14:27,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,11233,120 CHAUNCEY STREET,CHAUNCEY STREET,STUYVESANT AVENUE,MALCOLM X BOULEVARD,ADDRESS,Closed,2015-03-29 08:35:28,The Police Department responded to the complai...,2015-03-29 04:14:27,03 BROOKLYN
50645,30280732,2015-03-29 00:37:15,2015-03-29 01:02:39,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,10014,22 9 AVENUE,9 AVENUE,WEST 13 STREET,WEST 14 STREET,ADDRESS,Closed,2015-03-29 08:37:15,The Police Department reviewed your complaint ...,2015-03-29 01:02:39,02 MANHATTAN
19065,30280506,2015-03-29 00:43:16,2015-03-29 04:25:50,Noise - Vehicle,Car/Truck Music,Street/Sidewalk,10028,415 EAST 86 STREET,EAST 86 STREET,1 AVENUE,YORK AVENUE,ADDRESS,Closed,2015-03-29 08:43:16,The Police Department responded and upon arriv...,2015-03-29 04:25:50,08 MANHATTAN
116,30281090,2015-03-29 00:49:27,2015-03-29 04:25:53,Noise - Vehicle,Car/Truck Music,Street/Sidewalk,10028,420 EAST 86 STREET,EAST 86 STREET,1 AVENUE,YORK AVENUE,ADDRESS,Closed,2015-03-29 08:49:27,The Police Department responded and upon arriv...,2015-03-29 04:25:53,08 MANHATTAN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47242,32306260,2015-12-31 23:50:57,2016-01-01 10:58:00,Blocked Driveway,No Access,Street/Sidewalk,10453,1770 UNDERCLIFF AVENUE,UNDERCLIFF AVENUE,WEST 176 STREET,SEDGWICK AVENUE,ADDRESS,Closed,2016-01-01 07:50:00,The Police Department responded to the complai...,2016-01-01 10:58:00,05 BRONX
77179,32305071,2015-12-31 23:52:58,2016-01-01 07:41:00,Blocked Driveway,No Access,Street/Sidewalk,11372,34-06 73 STREET,73 STREET,34 AVENUE,35 AVENUE,ADDRESS,Closed,2016-01-01 07:52:00,The Police Department responded and upon arriv...,2016-01-01 07:41:00,03 QUEENS
41975,32306559,2015-12-31 23:55:32,2016-01-01 01:53:00,Illegal Parking,Blocked Hydrant,Street/Sidewalk,10032,524 WEST 169 STREET,WEST 169 STREET,AMSTERDAM AVENUE,AUDUBON AVENUE,ADDRESS,Closed,2016-01-01 07:55:00,The Police Department issued a summons in resp...,2016-01-01 01:53:00,12 MANHATTAN
80818,32306529,2015-12-31 23:56:58,2016-01-01 03:24:00,Illegal Parking,Blocked Sidewalk,Street/Sidewalk,11373,87-14 57 ROAD,57 ROAD,SEABURY STREET,HOFFMAN DRIVE,ADDRESS,Closed,2016-01-01 07:56:00,The Police Department responded and upon arriv...,2016-01-01 03:24:00,04 QUEENS
15623,32310363,2015-12-31 23:59:45,2016-01-01 00:55:00,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10034,71 VERMILYEA AVENUE,VERMILYEA AVENUE,ACADEMY STREET,WEST 204 STREET,ADDRESS,Closed,2016-01-01 07:59:00,The Police Department responded and upon arriv...,2016-01-01 00:55:00,12 MANHATTAN

In [38]:
# 2. Show complaints where the complaint type is either "Illegal Parking", "Noise - Street/Sidewalk", or "Blocked Driveway".
df_311[df_311['Complaint Type'].isin(['Illegal Parking','Noise - Street/Sidewalk','Blocked Driveway'])]

,Unique Key,Created Date,Closed Date,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,Street Name,Cross Street 1,Cross Street 2,Address Type,Status,Due Date,Resolution Description,Resolution Action Updated Date,Community Board
34299,30283432,2015-03-29 00:35:28,2015-03-29 04:14:27,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,11233,120 CHAUNCEY STREET,CHAUNCEY STREET,STUYVESANT AVENUE,MALCOLM X BOULEVARD,ADDRESS,Closed,2015-03-29 08:35:28,The Police Department responded to the complai...,2015-03-29 04:14:27,03 BROOKLYN
85595,30281254,2015-03-29 00:49:51,2015-03-29 02:02:21,Blocked Driveway,No Access,Street/Sidewalk,11385,1912 GROVE STREET,GROVE STREET,WOODWARD AVENUE,ST JOHNS ROAD,ADDRESS,Closed,2015-03-29 08:49:51,The Police Department responded and upon arriv...,2015-03-29 02:02:21,05 QUEENS
48736,30283901,2015-03-29 00:58:08,2015-03-29 04:44:02,Illegal Parking,Blocked Hydrant,Street/Sidewalk,10019,446 WEST 49 STREET,WEST 49 STREET,9 AVENUE,10 AVENUE,ADDRESS,Closed,2015-03-29 08:58:08,The Police Department responded to the complai...,2015-03-29 04:44:02,04 MANHATTAN
11022,30279563,2015-03-29 01:04:01,2015-03-29 01:23:04,Noise - Street/Sidewalk,Loud Talking,Street/Sidewalk,10014,NaN,NaN,NaN,NaN,INTERSECTION,Closed,2015-03-29 09:04:01,The Police Department responded to the complai...,2015-03-29 01:23:04,02 MANHATTAN
79089,30280534,2015-03-29 01:15:51,2015-03-29 02:03:34,Blocked Driveway,No Access,Street/Sidewalk,11358,198-18 32 AVENUE,32 AVENUE,FRANCIS LEWIS BOULEVARD,JORDAN STREET,ADDRESS,Closed,2015-03-29 09:15:51,The Police Department responded to the complai...,2015-03-29 02:03:34,11 QUEENS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47242,32306260,2015-12-31 23:50:57,2016-01-01 10:58:00,Blocked Driveway,No Access,Street/Sidewalk,10453,1770 UNDERCLIFF AVENUE,UNDERCLIFF AVENUE,WEST 176 STREET,SEDGWICK AVENUE,ADDRESS,Closed,2016-01-01 07:50:00,The Police Department responded to the complai...,2016-01-01 10:58:00,05 BRONX
77179,32305071,2015-12-31 23:52:58,2016-01-01 07:41:00,Blocked Driveway,No Access,Street/Sidewalk,11372,34-06 73 STREET,73 STREET,34 AVENUE,35 AVENUE,ADDRESS,Closed,2016-01-01 07:52:00,The Police Department responded and upon arriv...,2016-01-01 07:41:00,03 QUEENS
41975,32306559,2015-12-31 23:55:32,2016-01-01 01:53:00,Illegal Parking,Blocked Hydrant,Street/Sidewalk,10032,524 WEST 169 STREET,WEST 169 STREET,AMSTERDAM AVENUE,AUDUBON AVENUE,ADDRESS,Closed,2016-01-01 07:55:00,The Police Department issued a summons in resp...,2016-01-01 01:53:00,12 MANHATTAN
80818,32306529,2015-12-31 23:56:58,2016-01-01 03:24:00,Illegal Parking,Blocked Sidewalk,Street/Sidewalk,11373,87-14 57 ROAD,57 ROAD,SEABURY STREET,HOFFMAN DRIVE,ADDRESS,Closed,2016-01-01 07:56:00,The Police Department responded and upon arriv...,2016-01-01 03:24:00,04 QUEENS
15623,32310363,2015-12-31 23:59:45,2016-01-01 00:55:00,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10034,71 VERMILYEA AVENUE,VERMILYEA AVENUE,ACADEMY STREET,WEST 204 STREET,ADDRESS,Closed,2016-01-01 07:59:00,The Police Department responded and upon arriv...,2016-01-01 00:55:00,12 MANHATTAN

In [39]:
# 3. Show "Blocked Driveway" complaints where the incident ZIP is either 10007 or 10307.

df_311[(df_311['Complaint Type']=='Blocked Driveway') & (df_311['Incident Zip'].isin([10007,10307]))]

,Unique Key,Created Date,Closed Date,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,Street Name,Cross Street 1,Cross Street 2,Address Type,Status,Due Date,Resolution Description,Resolution Action Updated Date,Community Board
84929,30741450,2015-05-31 20:59:20,2015-05-31 22:38:13,Blocked Driveway,No Access,Street/Sidewalk,10307,17 SEACREST LANE,SEACREST LANE,SPRAGUE AVENUE,SUNSET LANE,ADDRESS,Closed,2015-06-01 04:59:00,The Police Department responded to the complai...,2015-05-31 22:38:13,03 STATEN ISLAND
78229,31158664,2015-07-25 18:30:12,2015-07-25 20:14:54,Blocked Driveway,No Access,Street/Sidewalk,10307,7336 AMBOY ROAD,AMBOY ROAD,FISHER AVENUE,WOOD AVENUE,ADDRESS,Closed,2015-07-26 02:30:12,The Police Department responded and upon arriv...,2015-07-25 20:14:54,03 STATEN ISLAND
53690,31519452,2015-09-12 21:22:00,2015-09-12 22:39:00,Blocked Driveway,No Access,Street/Sidewalk,10307,243 CHELSEA STREET,CHELSEA STREET,HYLAN BOULEVARD,CLERMONT AVENUE,ADDRESS,Closed,2015-09-13 05:22:15,The Police Department responded to the complai...,2015-09-12 22:39:00,03 STATEN ISLAND
61493,31693876,2015-10-06 14:25:00,2015-10-06 23:12:00,Blocked Driveway,No Access,Street/Sidewalk,10007,71 READE STREET,READE STREET,BROADWAY,CHURCH STREET,ADDRESS,Closed,2015-10-06 22:25:00,The Police Department responded to the complai...,2015-10-06 23:12:00,01 MANHATTAN
54978,31713260,2015-10-08 19:13:00,2015-10-08 23:39:00,Blocked Driveway,No Access,Street/Sidewalk,10007,77 READE STREET,READE STREET,BROADWAY,CHURCH STREET,ADDRESS,Closed,2015-10-09 03:13:00,The Police Department responded and upon arriv...,2015-10-08 23:39:00,01 MANHATTAN
47645,31884584,2015-10-31 23:45:30,2015-11-01 08:17:00,Blocked Driveway,No Access,Street/Sidewalk,10307,41 HALE STREET,HALE STREET,AMBOY ROAD,LENHART STREET,ADDRESS,Closed,2015-11-01 07:45:00,The Police Department issued a summons in resp...,2015-11-01 08:17:00,03 STATEN ISLAND
61211,32017774,2015-11-18 14:33:03,2015-11-18 14:49:44,Blocked Driveway,No Access,Street/Sidewalk,10007,8 WARREN STREET,WARREN STREET,BROADWAY,CHURCH STREET,ADDRESS,Closed,2015-11-18 22:33:03,The Police Department responded to the complai...,2015-11-18 14:49:44,01 MANHATTAN
13199,32038599,2015-11-21 10:29:47,2015-11-21 12:52:30,Blocked Driveway,Partial Access,Street/Sidewalk,10307,626 CRAIG AVENUE,CRAIG AVENUE,AMBOY ROAD,SUMMIT ROAD,ADDRESS,Closed,2015-11-21 18:29:47,The Police Department responded and upon arriv...,2015-11-21 12:52:30,03 STATEN ISLAND
82123,32131313,2015-12-04 14:23:00,2015-12-04 19:53:00,Blocked Driveway,Partial Access,Street/Sidewalk,10007,101 BARCLAY STREET,BARCLAY STREET,GREENWICH STREET,WASHINGTON STREET,ADDRESS,Closed,2015-12-04 22:23:00,The Police Department responded and upon arriv...,2015-12-04 19:53:00,01 MANHATTAN

In [40]:
# 4. Find all complaints where the street name starts with the letter 'E'.

df_311[df_311['Street Name'].str.startswith('E', na=False)]

,Unique Key,Created Date,Closed Date,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,Street Name,Cross Street 1,Cross Street 2,Address Type,Status,Due Date,Resolution Description,Resolution Action Updated Date,Community Board
19065,30280506,2015-03-29 00:43:16,2015-03-29 04:25:50,Noise - Vehicle,Car/Truck Music,Street/Sidewalk,10028,415 EAST 86 STREET,EAST 86 STREET,1 AVENUE,YORK AVENUE,ADDRESS,Closed,2015-03-29 08:43:16,The Police Department responded and upon arriv...,2015-03-29 04:25:50,08 MANHATTAN
116,30281090,2015-03-29 00:49:27,2015-03-29 04:25:53,Noise - Vehicle,Car/Truck Music,Street/Sidewalk,10028,420 EAST 86 STREET,EAST 86 STREET,1 AVENUE,YORK AVENUE,ADDRESS,Closed,2015-03-29 08:49:27,The Police Department responded and upon arriv...,2015-03-29 04:25:53,08 MANHATTAN
72193,30280817,2015-03-29 00:57:25,2015-03-29 02:25:31,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,11203,196 EAST 51 STREET,EAST 51 STREET,WINTHROP STREET,CLARKSON AVENUE,ADDRESS,Closed,2015-03-29 08:57:25,The Police Department responded to the complai...,2015-03-29 02:25:31,17 BROOKLYN
8400,30281419,2015-03-29 01:12:31,2015-03-29 01:47:54,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,10003,100 EAST 20 STREET,EAST 20 STREET,PARK AVENUE SOUTH,GRAMERCY PARK,ADDRESS,Closed,2015-03-29 09:12:31,Your request can not be processed at this time...,2015-03-29 01:47:54,06 MANHATTAN
83905,30280099,2015-03-29 01:33:12,2015-03-29 04:50:25,Noise - Vehicle,Car/Truck Horn,Street/Sidewalk,10029,169 EAST EAST 111 STREET,EAST 111 STREET,LEXINGTON AVENUE,3 AVENUE,ADDRESS,Closed,2015-03-29 09:33:12,The Police Department issued a summons in resp...,2015-03-29 04:50:25,11 MANHATTAN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6135,32305164,2015-12-31 13:40:53,2015-12-31 19:37:52,Noise - Commercial,Loud Music/Party,Store/Commercial,10029,112 EAST 116 ST-MARIN BOULEVARD,EAST 116 ST-MARIN BOULEVARD,PARK AVENUE,LEXINGTON AVENUE,ADDRESS,Closed,2015-12-31 21:40:53,The Police Department responded to the complai...,2015-12-31 19:37:52,11 MANHATTAN
85438,32307008,2015-12-31 14:43:17,2015-12-31 15:40:34,Blocked Driveway,No Access,Street/Sidewalk,11213,1231 EASTERN PARKWAY,EASTERN PARKWAY,ROCHESTER AVENUE,BUFFALO AVENUE,ADDRESS,Closed,2015-12-31 22:43:17,The Police Department responded and upon arriv...,2015-12-31 15:40:34,08 BROOKLYN
34787,32306573,2015-12-31 17:08:07,2015-12-31 18:57:26,Illegal Parking,Blocked Sidewalk,Street/Sidewalk,11210,622 EAST 28 STREET,EAST 28 STREET,FARRAGUT ROAD,FLATBUSH AVENUE,ADDRESS,Closed,2016-01-01 01:08:00,The Police Department responded to the complai...,2015-12-31 18:57:26,14 BROOKLYN
83902,32308422,2015-12-31 21:12:43,2015-12-31 22:50:08,Blocked Driveway,No Access,Street/Sidewalk,11236,1319 EAST 85 STREET,EAST 85 STREET,AVENUE M,AVENUE N,ADDRESS,Closed,2016-01-01 05:12:00,The Police Department responded and upon arriv...,2015-12-31 22:50:08,18 BROOKLYN
41275,32305962,2015-12-31 22:02:19,2015-12-31 23:02:07,Noise - Street/Sidewalk,Loud Talking,Street/Sidewalk,10029,8 EAST 108 STREET,EAST 108 STREET,5 AVENUE,MADISON AVENUE,ADDRESS,Closed,2016-01-01 06:02:00,The Police Department responded to the complai...,2015-12-31 23:02:08,11 MANHATTAN

In [41]:
# 5. Display the first 3 rows and the 2nd to 5th columns using integer-based indexing.

df_311.iloc[:3,1:5]

,Created Date,Closed Date,Complaint Type,Descriptor
87211,2015-03-29 00:33:03,2015-03-29 03:40:20,Noise - Commercial,Loud Music/Party
34299,2015-03-29 00:35:28,2015-03-29 04:14:27,Noise - Street/Sidewalk,Loud Music/Party
50645,2015-03-29 00:37:15,2015-03-29 01:02:39,Noise - Commercial,Loud Music/Party

In [42]:
# 6. Show Complaint Type, Created Date, and Status for ZIP code 11373 using label-based selection.

df_311.loc[df_311['Incident Zip']==11373, ['Complaint Type', 'Created Date', 'Status','Incident Zip']]

         Complaint Type        Created Date  Status  Incident Zip
50242   Noise - Vehicle 2015-03-29 16:31:02  Closed         11373
71983   Illegal Parking 2015-03-31 07:15:04  Closed         11373
26707  Blocked Driveway 2015-03-31 13:59:09  Closed         11373
13233   Illegal Parking 2015-04-01 03:18:00  Closed         11373
88572  Blocked Driveway 2015-04-02 17:02:00  Closed         11373
...                 ...                 ...     ...           ...
5687    Illegal Parking 2015-12-31 17:23:20  Closed         11373
12694  Blocked Driveway 2015-12-31 21:55:30  Closed         11373
39687   Illegal Parking 2015-12-31 22:43:14  Closed         11373
67979  Blocked Driveway 2015-12-31 22:52:24  Closed         11373
80818   Illegal Parking 2015-12-31 23:56:58  Closed         11373

[786 rows x 4 columns]

In [43]:
# 7. Filter complaints where the Created Date falls between October 1, 2015 and October 2, 2015.

start_date = pd.to_datetime('2015-10-01')
end_date = pd.to_datetime('2015-10-02')
df_311[(df_311['Created Date'].between(start_date, end_date))]

,Unique Key,Created Date,Closed Date,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,Street Name,Cross Street 1,Cross Street 2,Address Type,Status,Due Date,Resolution Description,Resolution Action Updated Date,Community Board
24140,31644959,2015-10-01 00:04:00,2015-10-01 03:05:00,Noise - Commercial,Loud Music/Party,Store/Commercial,11103,45-04 30 AVENUE,30 AVENUE,45 STREET,46 STREET,ADDRESS,Closed,2015-10-01 08:04:00,The Police Department responded to the complai...,2015-10-01 03:05:00,01 QUEENS
19130,31647644,2015-10-01 00:04:00,2015-10-01 01:57:00,Blocked Driveway,No Access,Street/Sidewalk,10467,3305 PARKSIDE PLACE,PARKSIDE PLACE,EAST 209 STREET,NaN,ADDRESS,Closed,2015-10-01 08:04:00,The Police Department responded and upon arriv...,2015-10-01 01:57:00,07 BRONX
71212,31651879,2015-10-01 00:06:00,2015-10-01 05:05:00,Noise - Commercial,Loud Talking,Club/Bar/Restaurant,10036,22 WEST 46 STREET,WEST 46 STREET,5 AVENUE,AVENUE OF THE AMERICAS,ADDRESS,Closed,2015-10-01 08:06:00,The Police Department responded to the complai...,2015-10-01 05:05:00,05 MANHATTAN
44840,31647234,2015-10-01 00:06:00,2015-10-01 07:44:00,Illegal Parking,Blocked Hydrant,Street/Sidewalk,11209,7718 3 AVENUE,3 AVENUE,77 STREET,78 STREET,ADDRESS,Closed,2015-10-01 08:06:00,The Police Department responded and upon arriv...,2015-10-01 07:44:00,10 BROOKLYN
35894,31649270,2015-10-01 00:08:00,2015-10-01 02:41:00,Noise - Street/Sidewalk,Loud Talking,Street/Sidewalk,10003,125 EAST 11 STREET,EAST 11 STREET,4 AVENUE,3 AVENUE,ADDRESS,Closed,2015-10-01 08:08:00,The Police Department responded to the complai...,2015-10-01 02:41:00,03 MANHATTAN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40113,31653296,2015-10-01 23:46:00,2015-10-02 00:12:00,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10029,2246 1 AVENUE,1 AVENUE,EAST 115 STREET,EAST 116 STREET,ADDRESS,Closed,2015-10-02 07:46:00,The Police Department responded to the complai...,2015-10-02 00:12:00,11 MANHATTAN
22958,31654195,2015-10-01 23:47:00,2015-10-02 02:07:00,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,10003,321 FIRST AVENUE,FIRST AVENUE,EAST 18 STREET,EAST 19 STREET,ADDRESS,Closed,2015-10-02 07:47:00,The Police Department responded to the complai...,2015-10-02 02:07:00,06 MANHATTAN
41382,31653191,2015-10-01 23:59:00,2015-10-02 04:11:00,Illegal Parking,Blocked Hydrant,Street/Sidewalk,11230,629 WESTMINSTER ROAD,WESTMINSTER ROAD,NEWKIRK AVENUE,FOSTER AVENUE,ADDRESS,Closed,2015-10-02 07:59:00,The Police Department responded and upon arriv...,2015-10-02 04:12:00,14 BROOKLYN
28705,31658395,2015-10-01 23:59:00,2015-10-02 01:10:00,Blocked Driveway,No Access,Street/Sidewalk,11102,23-41 30 DRIVE,30 DRIVE,23 STREET,CRESCENT STREET,ADDRESS,Closed,2015-10-02 07:59:00,The Police Department issued a summons in resp...,2015-10-02 01:10:00,01 QUEENS
62068,31656064,2015-10-01 23:59:00,2015-10-02 05:21:00,Noise - Commercial,Loud Music/Party,Store/Commercial,11238,990 ATLANTIC AVENUE,ATLANTIC AVENUE,GRAND AVENUE,CLASSON AVENUE,ADDRESS,Closed,2015-10-02 07:59:00,The Police Department responded to the complai...,2015-10-02 05:21:00,08 BROOKLYN

### Step 5: Calculate Response Time in Hours

To analyze how long it takes to respond to a 311 complaint, we'll calculate the **response time** by subtracting the `Created Date` from the `Closed Date`.

- Subtracting two datetime columns gives a **Timedelta** object.
- To convert the timedelta to a numeric value (in seconds), use `.dt.total_seconds()`.
- Finally, divide by 3600 to convert seconds to **hours**.

We will store the result in a new column called `Response Time (hrs)`.

In [44]:
# Your code here
df_311['Response Time (hrs)'] = (df_311['Closed Date'] - df_311['Created Date']).dt.total_seconds() / 3600

### Step 6: Analyze Response Times

**Classify as 'Fast' or 'Slow'**  
   Based on the `Response Time (hrs)`, classify each complaint as:
   - `'Fast'` if response time is **6 hours or less**
   - `'Slow'` if it took **more than 6 hours**

This helps in understanding how efficiently complaints were addressed.

In [45]:
# Classify responses based on a 6-hour threshold

df_311['Response Classification'] = df_311['Response Time (hrs)'].apply(lambda x: 'Fast' if x < 6 else 'Slow')

### Step 7: Average Response Time by Complaint Type

To understand which types of complaints take longer to resolve on average:

- Use `groupby()` on the `Complaint Type` column.
- Calculate the **mean** of `Response Time (hrs)` for each group.

In [46]:
# Mean response time by complaint type
df_311.groupby('Complaint Type')['Response Time (hrs)'].mean().sort_values(ascending=False).head(10)

Complaint Type
Graffiti                     7.888535
Derelict Vehicle             7.545651
Animal Abuse                 5.213205
Blocked Driveway             4.780392
Illegal Parking              4.451517
Homeless Encampment          4.392481
Vending                      3.941029
Bike/Roller/Skate Chronic    3.885261
Drinking                     3.843890
Noise - Vehicle              3.720984
Name: Response Time (hrs), dtype: float64

### Step 8: Load and Inspect ZIP Code Information

In this step, you'll load the ZIP code information dataset and inspect its structure. The file name is `zip_code_info.csv`

- How many ZIP codes are listed?
- What columns are available?
- View the first few rows to understand the kind of information it provides (e.g., population, borough).

In [47]:
# Load the ZIP code info dataset
zip_info = pd.read_csv("zip_code_info.csv")

# Basic inspection
print("Shape (rows, columns):", zip_info.shape)
print("\nColumn names:\n", zip_info.columns.tolist())
zip_info.head()

Shape (rows, columns): (196, 5)

Column names:
 ['zip', 'Borough', 'city', 'state_id', 'population']

     zip    Borough      city state_id  population
0  10001  MANHATTAN  New York       NY     29079.0
1  10002  MANHATTAN  New York       NY     75517.0
2  10003  MANHATTAN  New York       NY     53825.0
3  10004  MANHATTAN  New York       NY      3875.0
4  10005  MANHATTAN  New York       NY      9238.0

In [48]:
zip_info.info()

<class 'pandas.DataFrame'>
RangeIndex: 196 entries, 0 to 195
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   zip         196 non-null    int64
 1   Borough     196 non-null    str
 2   city        196 non-null    str
 3   state_id    196 non-null    str
 4   population  196 non-null    float64
dtypes: float64(1), int64(1), str(3)
memory usage: 7.8 KB

### Step 9: Find Complaints in the Most Populated ZIP Code

To understand how complaints are distributed in areas with dense populations:

1. Identify the ZIP code with the **highest population** from `zip_info`.
2. Filter the complaints dataframe to include only those that occurred in that ZIP.
3. Get the total number of complaints in that zip code.
4. Display a few sample complaints from that ZIP.

In [49]:
# Most populated ZIP code
most_populated_zip = zip_info.sort_values(by='population', ascending=False).iloc[0]['zip']

complaints_in_zip = df_311[df_311['Incident Zip'] == most_populated_zip]

print(f"Most populated ZIP code: {most_populated_zip}")
print(f"Number of complaints : {len(complaints_in_zip)}")
complaints_in_zip[['Complaint Type','Status','Created Date','Incident Zip']].head()

Most populated ZIP code: 11368
Number of complaints : 1244

            Complaint Type  Status        Created Date  Incident Zip
50571     Blocked Driveway  Closed 2015-03-29 09:07:17         11368
87473     Blocked Driveway  Closed 2015-03-29 12:11:23         11368
34908     Blocked Driveway  Closed 2015-03-29 19:17:40         11368
70544     Blocked Driveway  Closed 2015-03-29 23:03:16         11368
67988  Homeless Encampment  Closed 2015-03-30 19:41:04         11368

### Step 10: Merge Complaint Data with ZIP Code Demographics

We want to enrich the 311 dataset (`df_311`) with additional info from `zip_info`, such as population and borough name.

Here's what we do:

- Use `.merge()` to combine `df_311` and `zip_info`.
- Match `Incident Zip` from the 311 data with `zip` from the ZIP info.
- Use a **left join** to:
  - Keep all rows from `df_311` (even if some ZIPs don’t match).
  - Add population and borough data **only where a match exists**.

After merging:
- You'll see all columns from `zip_info`.
- The `zip` column (from `zip_info`) becomes redundant — it duplicates `Incident Zip` — so drop it.

In [50]:
# Merge all columns from zip_info, matching on ZIP code
df_merged = df_311.merge(zip_info, left_on='Incident Zip', right_on='zip', how='left')

# Drop the redundant 'zip' column from the merged DataFrame
df_merged.drop(columns='zip', inplace=True)

# Preview the result
df_merged.head()

,Unique Key,Created Date,Closed Date,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,Street Name,Cross Street 1,...,Due Date,Resolution Description,Resolution Action Updated Date,Community Board,Response Time (hrs),Response Classification,Borough,city,state_id,population
0,30283424,2015-03-29 00:33:03,2015-03-29 03:40:20,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,11206,162 THROOP AVENUE,THROOP AVENUE,HOPKINS STREET,...,2015-03-29 08:33:03,The Police Department responded to the complai...,2015-03-29 03:40:20,03 BROOKLYN,3.121389,Fast,BROOKLYN,Brooklyn,NY,89231.0
1,30283432,2015-03-29 00:35:28,2015-03-29 04:14:27,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,11233,120 CHAUNCEY STREET,CHAUNCEY STREET,STUYVESANT AVENUE,...,2015-03-29 08:35:28,The Police Department responded to the complai...,2015-03-29 04:14:27,03 BROOKLYN,3.649722,Fast,BROOKLYN,Brooklyn,NY,82711.0
2,30280732,2015-03-29 00:37:15,2015-03-29 01:02:39,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,10014,22 9 AVENUE,9 AVENUE,WEST 13 STREET,...,2015-03-29 08:37:15,The Police Department reviewed your complaint ...,2015-03-29 01:02:39,02 MANHATTAN,0.423333,Fast,MANHATTAN,New York,NY,29772.0
3,30280506,2015-03-29 00:43:16,2015-03-29 04:25:50,Noise - Vehicle,Car/Truck Music,Street/Sidewalk,10028,415 EAST 86 STREET,EAST 86 STREET,1 AVENUE,...,2015-03-29 08:43:16,The Police Department responded and upon arriv...,2015-03-29 04:25:50,08 MANHATTAN,3.709444,Fast,MANHATTAN,New York,NY,45679.0
4,30281090,2015-03-29 00:49:27,2015-03-29 04:25:53,Noise - Vehicle,Car/Truck Music,Street/Sidewalk,10028,420 EAST 86 STREET,EAST 86 STREET,1 AVENUE,...,2015-03-29 08:49:27,The Police Department responded and upon arriv...,2015-03-29 04:25:53,08 MANHATTAN,3.607222,Fast,MANHATTAN,New York,NY,45679.0

### Step 11: Analyze Complaint Types Across Boroughs with a Pivot Table

To summarize and compare complaint volumes across boroughs and types, we use a **pivot table**. Pivot tables are used when you want to **summarize grouped data** in a 2D format for easy comparison.

#### What is a pivot table?
A pivot table reshapes data:
- **Rows (`index`)** represent categories you want to group by (e.g., `Borough`).
- **Columns (`columns`)** represent subcategories (e.g., `Complaint Type`).
- **Values (`values`)** are the numbers you want to compute (e.g., count of complaints).
- **aggfunc** defines what to compute: `count`, `sum`, `mean`, etc.

####  In this case:
- We group complaints by **borough**.
- For each borough, we count the number of complaints of each **type**.
- We use `fill_value=0` to replace missing combinations with zero (no complaints of that type).

In [51]:
# Create a pivot table to count complaints by Borough and Complaint Type
pivot_table = df_merged.pivot_table(index='Borough', columns='Complaint Type', values='Unique Key', aggfunc='count', fill_value=0)
pivot_table.head()

Complaint Type,Animal Abuse,Bike/Roller/Skate Chronic,Blocked Driveway,Derelict Vehicle,Disorderly Youth,Drinking,Graffiti,Homeless Encampment,Illegal Fireworks,Illegal Parking,...,Noise - House of Worship,Noise - Park,Noise - Street/Sidewalk,Noise - Vehicle,Panhandling,Posting Advertisement,Squeegee,Traffic,Urinating in Public,Vending
Borough,,,,,,,,,,,,,,,,,,,,,
BRONX,454,5,3873,581,12,47,0,81,10,2357,...,26,180,2709,1018,3,7,0,104,14,92
BROOKLYN,749,42,8945,1698,26,74,19,267,21,8971,...,109,462,4171,1611,14,14,0,335,39,161
MANHATTAN,422,73,771,177,24,89,8,876,8,3726,...,56,398,6201,1641,69,8,1,450,66,730
QUEENS,611,18,10060,2551,21,113,15,172,16,6955,...,124,196,1678,872,13,10,0,383,49,159
STATEN ISLAND,156,1,645,529,9,64,1,21,3,1433,...,4,17,231,123,7,154,0,50,6,6

### Step 12: Convert Pivot Table to Long Format with `melt()`

We previously created a **pivot table** to compare complaint counts by borough and type. Now, we'll use `melt()` to convert that wide-format table back into a **long-format** DataFrame.


#### What is `melt()`?

- `melt()` is used to **unpivot** or **flatten** a DataFrame.
- It turns columns into rows, which is useful when:
  - You want to plot or analyze categorical data more easily.
  - You need a **tidy format**: one row per observation.


#### In this case:
- `id_vars='Borough'` means we'll keep that column as-is.
- All other columns (complaint types) become values in a new column: `'Complaint Type'`.
- Their counts go into `'Complaint Count'`.

This is useful for **grouped bar plots**, heatmaps, or exporting clean data.

In [52]:
# Melt the pivot table to have a long format DataFrame with Borough, Complaint Type, and Count columns
melted = pivot_table.reset_index().melt(id_vars='Borough', var_name='Complaint Type', value_name='Count')
melted.head()

         Borough Complaint Type  Count
0          BRONX   Animal Abuse    454
1       BROOKLYN   Animal Abuse    749
2      MANHATTAN   Animal Abuse    422
3         QUEENS   Animal Abuse    611
4  STATEN ISLAND   Animal Abuse    156

### Step 13: Save Pivot Table and ZIP Info for Visualization

We've created a **pivot table** summarizing complaint counts by borough and complaint type (`pivot`).  
Now, we'll save this summary for future use in visualizations (e.g., bar charts, heatmaps).

Do these:
- Save the `pivot` table to a **CSV file** for general use.  
- Use the code below to export both the `pivot` table and the full `zip_info` DataFrame to an **Excel file** with two separate sheets:
  - First sheet: `"Complaint Summary"` → the pivot table
  - Second sheet: `"ZIP Info"` → the ZIP code dataset

**Note:** To use `pd.ExcelWriter` for saving `.xlsx` files, you need to have the `openpyxl` library installed.  
If you get an error, install it using:
```
pip install openpyxl
```

In [53]:
# Save to CSV
pivot_table.to_csv('complaints_pivot_table.csv')

In [54]:
# Save both DataFrames to separate sheets in one Excel file
with pd.ExcelWriter("complaint_summary.xlsx") as writer:
    pivot_table.to_excel(writer, sheet_name="Complaint Summary")
    zip_info.to_excel(writer, sheet_name="ZIP Info", index=False)

# Bonus Section: Performance Comparison: Vectorized Operations vs. apply() vs. iterrows()

When working with pandas, **how** you write your operations can make a huge difference in performance — especially on large datasets.

In this example, we compare three common ways to assign a new column based on `Response Time (hrs)`. We have already solved this problem but let's revisit it:

**Question was**: Label each row as `'Fast'` if the response time is 6 hours or less, and `'Slow'` otherwise.

You can solve this in different ways:

#### 1. `apply()` with lambda as we did
#### 2. `np.where` – Vectorized
#### 3. `iterrows()` – Avoid if Possible. This is like a for loop on rows of the dataframe

**time.time() is used to compute the time taken to compute a block of code**

`np.where` works like this and you can assign it to a column:
```python
np.where(df['col'] <= x, 'A', 'B')

`iterrows()` loops over a DataFrame row by row, returning each row as a (index, Series) pair.

Use only when absolutely necessary (e.g., complex logic that can't be vectorized) as this is very time-consuming.

```python
for index, row in df.iterrows():
    # Access values like a dictionary
    value = row['ColumnName']
    # Perform operations here

In [55]:
print(df_311.columns)

Index(['Unique Key', 'Created Date', 'Closed Date', 'Complaint Type',
       'Descriptor', 'Location Type', 'Incident Zip', 'Incident Address',
       'Street Name', 'Cross Street 1', 'Cross Street 2', 'Address Type',
       'Status', 'Due Date', 'Resolution Description',
       'Resolution Action Updated Date', 'Community Board',
       'Response Time (hrs)', 'Response Classification'],
      dtype='str')

In [56]:
import time
import numpy as np

# 1. Vectorized with np.where
start = time.time()
df_311['Speed Category'] = np.where(df_311['Response Time (hrs)'] <= 6, 'Fast', 'Slow')
print("np.where time:", round(time.time() - start, 4), "seconds")

# 2. apply() with lambda
start = time.time()
df_311['Speed Category'] = df_311['Response Time (hrs)'].apply(lambda x: 'Fast' if x <= 6 else 'Slow')
print("apply() time:", round(time.time() - start, 4), "seconds")

# 3. iterrows()
start = time.time()
speed_labels = []
for _, row in df_311.iterrows():
    speed_labels.append('Fast' if row['Response Time (hrs)'] <= 6 else 'Slow')
df_311['Speed Category'] = speed_labels
print("iterrows() time:", round(time.time() - start, 4), "seconds")

np.where time: 0.002 seconds
apply() time: 0.0069 seconds
iterrows() time: 0.785 seconds

### A randomly generated DataFrame
to show the difference of vectorized operations better

In [57]:
import pandas as pd
import numpy as np
import time

# Create a large DataFrame
df_test = pd.DataFrame({'value': np.arange(1000000)})

# 1. Vectorized
start = time.time()
df_test['squared_vec'] = df_test['value'] ** 2
print("Vectorized time:", round(time.time() - start, 4), "seconds")

# 2. apply() with lambda
start = time.time()
df_test['squared_apply'] = df_test['value'].apply(lambda x: x ** 2)
print("apply() time:", round(time.time() - start, 4), "seconds")

# 3. iterrows()
start = time.time()
squared = []
for _, row in df_test.iterrows():
    squared.append(row['value'] ** 2)
df_test['squared_iterrows'] = squared
print("iterrows() time:", round(time.time() - start, 4), "seconds")

Vectorized time: 0.0007 seconds
apply() time: 0.1419 seconds
iterrows() time: 5.677 seconds